# -*- coding: utf-8 -*-
"""JOB SCRAPING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMNw1YZfs1nlyE7PABveIvBeUjVyk9Vz
"""

# Install necessary libraries. If you encounter issues, uncomment the !pip uninstall lines and then reinstall specific versions.
#!pip uninstall numpy pandas
#!pip install numpy==1.26.3 pandas==2.2.2
!pip install -U python-jobspy

import csv
from jobspy import scrape_jobs

# Scrape job postings based on specified criteria
jobs = scrape_jobs(
    site_name=["indeed", "linkedin", "google"],
    search_term=str(input()),
    google_search_term= str(input()) + "jobs in Hong Kong",
    location="Hong Kong",
    results_wanted=1000,
    hours_old=720,
    country_indeed='Hong Kong',
    linkedin_fetch_description=True,
)
print(f"Found {len(jobs)} jobs")
print(jobs.head())

# Save the scraped job data to a CSV file for persistence
jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False)

import pandas as pd
# Load the saved job data into a pandas DataFrame
df_jobs = pd.read_csv('jobs.csv')
print(f"Successfully loaded {len(df_jobs)} jobs from jobs.csv.")
print(df_jobs.head())


import sys
# Install spaCy library for natural language processing
!pip install spacy
# Download the English small model for spaCy
!python -m spacy download en_core_web_sm

print("spaCy installed and 'en_core_web_sm' model downloaded.")


import spacy

# Load the downloaded spaCy language model
nlp = spacy.load("en_core_web_sm")

print("spaCy language model 'en_core_web_sm' loaded.")


import re

# Define a function to extract duties and responsibilities from job descriptions
def extract_duties_responsibilities(description):
    if pd.isna(description):
        return []
    doc = nlp(description)
    duties = []
    # Common patterns for duties/responsibilities sections
    duty_keywords = [
        "responsibilities", "duties", "will be responsible for", "tasks include",
        "key accountabilities", "you will", "support", "manage", "develop", "implement",
        "perform", "ensure", "collaborate", "lead", "maintain", "create", "design",
        "contribute", "prepare", "conduct", "analyze", "report"
    ]

    # Heuristic: Look for bullet points or numbered lists often used for duties
    for line in description.split('\n'):
        line = line.strip()
        if re.match(r'^[-*\u2022\s]*\s*[A-Za-z0-9]', line):
            duties.append(line)
        elif re.match(r'^\d+\.\s*[A-Za-z0-9]', line):
            duties.append(line)

    # If no bullet points found, try to extract sentences containing duty keywords
    if not duties:
        for sent in doc.sents:
            sentence_text = sent.text.lower()
            if any(keyword in sentence_text for keyword in duty_keywords):
                duties.append(sent.text)

    return duties

print("Function 'extract_duties_responsibilities' defined.")


import pandas as pd

# Reload the DataFrame to ensure the latest version is used (optional if already loaded)
df_jobs = pd.read_csv('jobs.csv')

# Apply the duty extraction function to the 'description' column
df_jobs['extracted_duties'] = df_jobs['description'].apply(extract_duties_responsibilities)
print(df_jobs[['title', 'description', 'extracted_duties']].head())


import csv
# Save the DataFrame with the newly extracted duties back to jobs.csv
df_jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False)
print("DataFrame with extracted duties saved to jobs.csv")


from google.colab import files
# Provide a download link for the updated CSV file
files.download('jobs.csv')

